{% set name = "pyspellchecker" %}
{% set version = "0.5.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 68af08ae5ffb3ac3d9d01ef421de9310eb3aa68ab7aa5913de846e1f3c0bb76c

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - python

test:
  imports:
    - spellchecker

about:
  home: https://github.com/barrust/pyspellchecker
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Pure python spell checker based on work by Peter Norvig

extra:
  recipe-maintainers:
    - dschreij
    - smathot
