{% set name = "pyspellchecker" %}
{% set version = "0.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0c13f129a18fb13dd028d1da9f3197f838cb6ec68b67a89092fe8406b2ec3170

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  imports:
    - spellchecker

about:
  home: https://github.com/barrust/pyspellchecker
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Pure python spell checker based on work by Peter Norvig

extra:
  recipe-maintainers:
    - dschreij
    - smathot
